make:
	g++ -Wall -c sequence1.cpp
	g++ -Wall -c sequence_exam.cpp
	g++ sequence_exam.o sequence1.o -o sequence_exam
make2: 
	g++ -Wall -c sequence1.cpp
	g++ -Wall -c sequence_test.cpp
	g++ sequence_test.o sequence1.o -o sequence_test
make3:
	g++ -Wall -c sequence1.cpp
	g++ -Wall -c sequence_exam.cxx
	g++ sequence_exam.o sequence1.o -o sequence_exam

