make:
	g++ -Wall -c sequence2.cpp
	g++ -Wall -c seq_ex2.cpp
	g++ seq_ex2.o sequence2.o -o sequence_exam
make2: 
	g++ -Wall -c sequence2.cpp
	g++ -Wall -c sequence_test.cpp
	g++ sequence_test.o sequence2.o -o sequence_test


